perturbate : perturbate_generate.cpp
	g++ perturbate_generate.cpp -std=c++11 -lsfml-window -lsfml-system -lsfml-graphics -lgmpxx -lgmp -g -Ofast -o perturbate 

clean :
	rm perturbate perturbate_data.txt
